### ISSUE TITLE
version 0.2.0+1 breaks with latest flutter master channel

### ISSUE THREAD

**Issue by soloman817** [jamesblasco/modal_bottom_sheet#69]
flutter doctor shows:

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.109, on Mac OS X 10.15.6 19G2021, locale en-GB)
```

```
modal_bottom_sheet: ^0.2.0+1
```

during compiling, it fail with:
```
../../../.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.0+1/lib/src/bottom_sheet.dart:295:43: Error: Too few positional arguments: 1 required, 0 given.
        _velocityTracker = VelocityTracker();
                                          ^
../../../Sandbox/flutter/packages/flutter/lib/src/gestures/velocity_tracker.dart:152:3: Context: Found this candidate, but the arguments don't match.
  VelocityTracker(this.kind);
  ^^^^^^^^^^^^^^^
```

Looks like flutter changed the interface:

```dart
/// Computes a pointer's velocity based on data from [PointerMoveEvent]s.
///
/// The input data is provided by calling [addPosition]. Adding data is cheap.
///
/// To obtain a velocity, call [getVelocity] or [getVelocityEstimate]. This will
/// compute the velocity based on the data added so far. Only call these when
/// you need to use the velocity, as they are comparatively expensive.
///
/// The quality of the velocity estimation will be better if more data points
/// have been received.
class VelocityTracker {
  /// Create a new velocity tracker for a pointer [kind].
  VelocityTracker(this.kind);
```

**Comment by jamesblasco** [comment]
Thanks for reporting this issue. 

I will create a fix in a separated branch

**Comment by wilsonowilson** [comment]
It also breaks the dev and beta channel

**Comment by offline-first** [comment]
Workaround
`VelocityTracker([this.kind = PointerDeviceKind.touch]);`

**Comment by Ludwigvsch** [comment]
Where do I implement that?

**Comment by Ludwigvsch** [comment]
> Workaround
> 
> `VelocityTracker([this.kind = PointerDeviceKind.touch]);`

Where do I implement that?

**Comment by offline-first** [comment]
open the VelocityTracker class from the Plugin and replace the constructor
 /packages/flutter/lib/src/gestures/velocity_tracker.dart:152:3

**Comment by jamesblasco** [comment]
Hi everyone 👋 
I've just published a pre-release version [0.2.1-dev](https://pub.dev/packages/modal_bottom_sheet/versions/0.2.1-dev) that solves this issue.

**Comment by mark-apn** [comment]
Thanks for fixing it. Please increment the version with a whole point when it contains breaking changes. This morning our project broke because we had ^0.2.0 as a dependency. Probably a good moment to go to 1.0 :-)

**Comment by emre88tosun** [comment]
I am still getting the same error with Flutter version 1.20.4 & ^0.2.1+1-dev. Any advice?

**Comment by mark-apn** [comment]
Downgrade to version 0.2.0 and remove the ^ in front of your version

**Comment by emre88tosun** [comment]
@mark-apn Thank you so much, now it's working.

**Comment by jamesblasco** [comment]
@mark-apn thanks. I didn't know that pre-release versions worked also semantic versioning. I will do that for now on

**Comment by Diora-Inc** [comment]
dependencies:
  modal_bottom_sheet: ^0.2.1-dev

$ flutter pub get

This should fix it

**Comment by slightfoot** [comment]
@jamesblasco They have now changed it again. They are deprecating the constructor with an optional arg in `v1.22.0-12.1.pre` and now have `VelocityTracker.withKind(this.kind)`; It would be good if you put that version in the Changelog.

Ref: https://github.com/flutter/flutter/pull/66043

**Comment by jamesblasco** [comment]
I reversed the changes in a new version  0.2.1+2.

I will publish soon a 1.0.0+dev with `VelocityTracker.withKind(this.kind)` and another brake change inside the package
